import '../models/self_brand_profile.dart';
import '../models/self_brand_post.dart';

class SelfBrandService {
  static final Map<String, SelfBrandProfile> _profiles = {
    '1111': SelfBrandProfile(
      id: '1',
      moveNumber: '1111',
      phoneNumber: '123.456.7890',
      title: 'YOGA',
      backgroundImage: 'assets/images/yoga.jpg',
      description:
          '10년 경력의 요가 강사입니다. 아쉬탕가, 빈야사, 하타 요가를 전문적으로 지도하고 있으며, 개인과 그룹 수업을 모두 진행합니다. 건강한 라이프스타일과 마음의 평화를 찾는 여정을 함께하고 싶습니다.',
      telegramUrl: 'https://t.me/yogini_miran',
      xUrl: 'https://x.com/evaminjeong',
      youtubeUrl: 'https://m.youtube.com/@에일린mindyoga',
      homepageUrl: 'https://m.youtube.com/@에일린mindyoga',
      posts: [
        SelfBrandPost(
          id: '1',
          title: '초보자를 위한 아침 요가 루틴',
          content:
              '아침에 일어나서 할 수 있는 간단한 요가 동작들을 소개합니다. 이 루틴은 몸을 깨우고 하루를 활기차게 시작하는데 도움이 됩니다...',
          imageUrl: 'assets/images/yoga_post1.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 1)),
          likes: 128,
          comments: 23,
        ),
        SelfBrandPost(
          id: '2',
          title: '스트레스 해소를 위한 호흡법',
          content: '일상 생활에서 쌓인 스트레스를 해소하는데 도움이 되는 요가 호흡법을 알려드립니다...',
          imageUrl: 'assets/images/yoga_post2.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 3)),
          likes: 156,
          comments: 18,
        ),
        SelfBrandPost(
          id: '3',
          title: '요가로 바로잡는 거북목',
          content: '현대인들의 고질병인 거북목 증후군을 완화하는데 도움이 되는 요가 동작들을 소개합니다...',
          imageUrl: 'assets/images/yoga_post3.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 5)),
          likes: 202,
          comments: 34,
        ),
        SelfBrandPost(
          id: '4',
          title: '하타 요가의 기본 동작',
          content: '하타 요가의 기본이 되는 12가지 아사나를 자세히 설명합니다...',
          imageUrl: 'assets/images/yoga_post4.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 7)),
          likes: 167,
          comments: 27,
        ),
        SelfBrandPost(
          id: '5',
          title: '요가와 명상의 조화',
          content: '요가와 명상을 함께 하면 좋은 점과 실천 방법을 알려드립니다...',
          imageUrl: 'assets/images/yoga_post5.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 9)),
          likes: 143,
          comments: 19,
        ),
      ],
    ),
    '2222': SelfBrandProfile(
      id: '2',
      moveNumber: '2222',
      phoneNumber: '212.555.0123',
      title: 'REAL ESTATE',
      backgroundImage: 'assets/images/real_estate.jpg',
      description:
          '15년 경력의 부동산 전문가입니다. 강남 지역 아파트 및 상가 거래를 전문으로 하고 있으며, 투자 상담도 진행합니다. 고객의 니즈를 정확히 파악하여 최적의 매물을 추천해드립니다.',
      telegramUrl: 'https://t.me/s/sedaily_real_estate',
      xUrl: 'https://x.com/realestate_aid',
      youtubeUrl: 'https://m.youtube.com/channel/UCXvGtSJUybn-j_grFsWJfuw',
      homepageUrl: 'https://m.youtube.com/channel/UCXvGtSJUybn-j_grFsWJfuw',
      posts: [
        SelfBrandPost(
          id: '1',
          title: '2024년 부동산 시장 전망',
          content: '올해 부동산 시장의 주요 트렌드와 투자 전략을 분석했습니다...',
          imageUrl: 'assets/images/real_estate_post1.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 2)),
          likes: 245,
          comments: 42,
        ),
        SelfBrandPost(
          id: '2',
          title: '상가 투자의 핵심 포인트',
          content: '상가 투자시 반드시 체크해야 할 10가지 핵심 사항을 정리했습니다...',
          imageUrl: 'assets/images/real_estate_post2.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 4)),
          likes: 188,
          comments: 31,
        ),
        SelfBrandPost(
          id: '3',
          title: '입지 분석의 기술',
          content: '성공적인 부동산 투자의 기본이 되는 입지 분석 방법을 소개합니다...',
          imageUrl: 'assets/images/real_estate_post3.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 6)),
          likes: 203,
          comments: 37,
        ),
        SelfBrandPost(
          id: '4',
          title: '청약 제도 완벽 가이드',
          content: '주택 청약 제도의 최신 변경사항과 유의점을 정리했습니다...',
          imageUrl: 'assets/images/real_estate_post4.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 8)),
          likes: 167,
          comments: 29,
        ),
        SelfBrandPost(
          id: '5',
          title: '수익형 부동산의 종류',
          content: '다양한 수익형 부동산의 특징과 장단점을 비교 분석했습니다...',
          imageUrl: 'assets/images/real_estate_post5.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 10)),
          likes: 178,
          comments: 25,
        ),
      ],
    ),
    '3333': SelfBrandProfile(
      id: '3',
      moveNumber: '3333',
      phoneNumber: '310.555.0123',
      title: 'CAR DEALER',
      backgroundImage: 'assets/images/car_dealer.jpg',
      description:
          '20년 경력의 자동차 딜러입니다. 수입차부터 국산차까지 폭넓은 경험을 바탕으로 고객님께 최적의 차량을 추천해드립니다. 구매부터 관리까지 원스톱 서비스를 제공합니다.',
      telegramUrl: 'https://t.me/s/Auto_Jinwoo',
      xUrl: 'https://x.com/trucksalesguy',
      youtubeUrl: 'https://m.youtube.com/@angyuho85',
      homepageUrl: 'https://m.youtube.com/@angyuho85',
      posts: [
        SelfBrandPost(
          id: '1',
          title: '2024년 신차 라인업 소개',
          content: '올해 출시 예정인 주요 브랜드의 신차 모델들을 소개합니다...',
          imageUrl: 'assets/images/car_post1.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 1)),
          likes: 234,
          comments: 45,
        ),
        SelfBrandPost(
          id: '2',
          title: '전기차 구매 가이드',
          content: '전기차 구매시 고려해야 할 주요 사항들을 정리했습니다...',
          imageUrl: 'assets/images/car_post2.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 3)),
          likes: 198,
          comments: 36,
        ),
        SelfBrandPost(
          id: '3',
          title: '중고차 매입 시 체크포인트',
          content: '중고차 구매시 반드시 확인해야 할 사항들을 알려드립니다...',
          imageUrl: 'assets/images/car_post3.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 5)),
          likes: 167,
          comments: 29,
        ),
        SelfBrandPost(
          id: '4',
          title: '차량 관리의 기본',
          content: '차량의 수명을 늘리는 기본적인 관리 방법을 소개합니다...',
          imageUrl: 'assets/images/car_post4.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 7)),
          likes: 145,
          comments: 22,
        ),
        SelfBrandPost(
          id: '5',
          title: 'SUV vs 세단 비교',
          content: 'SUV와 세단의 장단점을 실제 사용 경험을 바탕으로 비교했습니다...',
          imageUrl: 'assets/images/car_post5.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 9)),
          likes: 189,
          comments: 33,
        ),
      ],
    ),
    '4444': SelfBrandProfile(
      id: '4',
      moveNumber: '4444',
      phoneNumber: '312.555.0123',
      title: 'PHOTOGRAPHER',
      backgroundImage: 'assets/images/photographer.jpg',
      description:
          '웨딩, 프로필, 부동산 등 다양한 분야의 사진 촬영 서비스를 제공합니다. 자연스러운 순간을 포착하여 특별한 추억을 만들어드립니다. 개인화된 맞춤 촬영으로 고객님의 니즈를 충족시켜드립니다.',
      telegramUrl: 'https://t.me/s/photo_gallery_f',
      xUrl: 'https://x.com/kchae',
      youtubeUrl: 'https://m.youtube.com/c/PhotographerJoowonKim',
      homepageUrl: 'https://m.youtube.com/c/PhotographerJoowonKim',
      posts: [
        SelfBrandPost(
          id: '1',
          title: '웨딩 촬영의 모든 것',
          content: '웨딩 촬영의 준비부터 마무리까지 전 과정을 상세히 설명합니다...',
          imageUrl: 'assets/images/photo_post1.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 2)),
          likes: 256,
          comments: 48,
        ),
        SelfBrandPost(
          id: '2',
          title: '인물사진 촬영 팁',
          content: '자연스럽고 매력적인 인물사진을 위한 촬영 노하우를 공유합니다...',
          imageUrl: 'assets/images/photo_post2.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 4)),
          likes: 198,
          comments: 35,
        ),
        SelfBrandPost(
          id: '3',
          title: '야경 촬영 테크닉',
          content: '도시의 밤을 아름답게 담아내는 야경 촬영 방법을 소개합니다...',
          imageUrl: 'assets/images/photo_post3.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 6)),
          likes: 223,
          comments: 41,
        ),
        SelfBrandPost(
          id: '4',
          title: '제품 사진 촬영 가이드',
          content: '상품 사진의 퀄리티를 높이는 조명과 구도 테크닉을 알려드립니다...',
          imageUrl: 'assets/images/photo_post4.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 8)),
          likes: 167,
          comments: 28,
        ),
        SelfBrandPost(
          id: '5',
          title: '풍경 사진 작법',
          content: '감동적인 풍경 사진을 위한 구도와 카메라 설정을 설명합니다...',
          imageUrl: 'assets/images/photo_post5.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 10)),
          likes: 189,
          comments: 32,
        ),
      ],
    ),
    '5555': SelfBrandProfile(
      id: '5',
      moveNumber: '5555',
      phoneNumber: '310.090.8888',
      title: 'FITNESS TRAINER',
      backgroundImage: 'assets/images/fitness.jpg',
      description: '10년 경력의 퍼스널 트레이너입니다. 체계적인 운동 프로그램과 맞춤형 식단 관리를 제공합니다.',
      telegramUrl: 'https://t.me/fitness_trainer',
      xUrl: 'https://x.com/fitness_trainer',
      youtubeUrl: 'https://youtube.com/@fitness_trainer',
      homepageUrl: 'https://fitnesstrainer.com',
      posts: [
        SelfBrandPost(
          id: '1',
          title: '효과적인 체지방 감량 방법',
          content: '과학적으로 입증된 체지방 감량 운동과 식단 관리 방법을 소개합니다...',
          imageUrl: 'assets/images/fitness_post1.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 1)),
          likes: 245,
          comments: 42,
        ),
        SelfBrandPost(
          id: '2',
          title: '홈트레이닝 가이드',
          content: '집에서도 할 수 있는 효과적인 운동 루틴을 알려드립니다...',
          imageUrl: 'assets/images/fitness_post2.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 3)),
          likes: 188,
          comments: 31,
        ),
        SelfBrandPost(
          id: '3',
          title: '건강한 식단 구성하기',
          content: '목표에 맞는 영양소 섭취와 식단 구성 방법을 설명합니다...',
          imageUrl: 'assets/images/fitness_post3.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 5)),
          likes: 203,
          comments: 37,
        ),
        SelfBrandPost(
          id: '4',
          title: '스트레칭의 중요성',
          content: '운동 전후 스트레칭이 중요한 이유와 올바른 방법을 소개합니다...',
          imageUrl: 'assets/images/fitness_post4.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 7)),
          likes: 167,
          comments: 29,
        ),
        SelfBrandPost(
          id: '5',
          title: '근육 회복과 휴식',
          content: '효과적인 근육 회복을 위한 휴식과 관리 방법을 알려드립니다...',
          imageUrl: 'assets/images/fitness_post5.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 9)),
          likes: 156,
          comments: 27,
        ),
      ],
    ),
    '6666': SelfBrandProfile(
      id: '6',
      moveNumber: '6666',
      phoneNumber: '315.988.1234',
      title: 'DIGITAL MARKETING',
      backgroundImage: 'assets/images/marketing.jpg',
      description: '디지털 마케팅 전문가입니다. SNS 마케팅, 콘텐츠 전략, 브랜드 구축을 도와드립니다.',
      telegramUrl: 'https://t.me/digital_marketer',
      xUrl: 'https://x.com/digital_marketer',
      youtubeUrl: 'https://youtube.com/@digital_marketer',
      homepageUrl: 'https://digitalmarketer.com',
      posts: [
        SelfBrandPost(
          id: '1',
          title: 'SNS 마케팅 트렌드',
          content: '2024년 주목해야 할 SNS 마케팅 트렌드와 전략을 분석합니다...',
          imageUrl: 'assets/images/marketing_post1.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 2)),
          likes: 312,
          comments: 45,
        ),
        SelfBrandPost(
          id: '2',
          title: '콘텐츠 마케팅 전략',
          content: '효과적인 콘텐츠 제작과 배포 전략을 공유합니다...',
          imageUrl: 'assets/images/marketing_post2.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 4)),
          likes: 289,
          comments: 38,
        ),
        SelfBrandPost(
          id: '3',
          title: '브랜드 아이덴티티 구축',
          content: '강력한 브랜드 아이덴티티를 만드는 방법을 설명합니다...',
          imageUrl: 'assets/images/marketing_post3.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 6)),
          likes: 267,
          comments: 41,
        ),
        SelfBrandPost(
          id: '4',
          title: '이메일 마케팅 가이드',
          content: '효과적인 이메일 마케팅 캠페인 설계와 실행 방법을 소개합니다...',
          imageUrl: 'assets/images/marketing_post4.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 8)),
          likes: 234,
          comments: 33,
        ),
        SelfBrandPost(
          id: '5',
          title: '구글 애즈 최적화',
          content: '구글 광고 성과를 높이는 실전 팁을 공유합니다...',
          imageUrl: 'assets/images/marketing_post5.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 10)),
          likes: 198,
          comments: 29,
        ),
      ],
    ),
    '7777': SelfBrandProfile(
      id: '7',
      moveNumber: '7777',
      phoneNumber: '310.988.1234',
      title: 'PET CARE',
      backgroundImage: 'assets/images/petcare.jpg',
      description: '전문 펫시터입니다. 반려동물의 건강한 생활과 행복한 돌봄을 책임집니다.',
      telegramUrl: 'https://t.me/pet_care',
      xUrl: 'https://x.com/pet_care',
      youtubeUrl: 'https://youtube.com/@pet_care',
      homepageUrl: 'https://petcare.com',
      posts: [
        SelfBrandPost(
          id: '1',
          title: '반려견 행동 교정 팁',
          content: '흔한 반려견 문제 행동과 교정 방법을 알려드립니다...',
          imageUrl: 'assets/images/petcare_post1.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 1)),
          likes: 278,
          comments: 52,
        ),
        SelfBrandPost(
          id: '2',
          title: '반려묘 건강관리',
          content: '고양이의 건강한 생활을 위한 관리 방법을 소개합니다...',
          imageUrl: 'assets/images/petcare_post2.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 3)),
          likes: 245,
          comments: 47,
        ),
        SelfBrandPost(
          id: '3',
          title: '반려동물 영양 가이드',
          content: '연령별, 상황별 적절한 영양 공급 방법을 설명합니다...',
          imageUrl: 'assets/images/petcare_post3.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 5)),
          likes: 234,
          comments: 43,
        ),
        SelfBrandPost(
          id: '4',
          title: '반려동물 응급처치',
          content: '긴급 상황 시 필요한 기본적인 응급처치 방법을 알려드립니다...',
          imageUrl: 'assets/images/petcare_post4.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 7)),
          likes: 312,
          comments: 67,
        ),
        SelfBrandPost(
          id: '5',
          title: '반려동물 미용 관리',
          content: '집에서 할 수 있는 기본적인 미용 관리 방법을 소개합니다...',
          imageUrl: 'assets/images/petcare_post5.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 9)),
          likes: 198,
          comments: 34,
        ),
      ],
    ),
    '8888': SelfBrandProfile(
      id: '8',
      moveNumber: '8888',
      phoneNumber: '510.223.4455',
      title: 'WEDDING PLANNER',
      backgroundImage: 'assets/images/wedding.jpg',
      description: '10년 경력의 웨딩플래너입니다. 특별한 순간을 완벽하게 준비해드립니다.',
      telegramUrl: 'https://t.me/wedding_planner',
      xUrl: 'https://x.com/wedding_planner',
      youtubeUrl: 'https://youtube.com/@wedding_planner',
      homepageUrl: 'https://weddingplanner.com',
      posts: [
        SelfBrandPost(
          id: '1',
          title: '2024 웨딩 트렌드',
          content: '올해의 웨딩 트렌드와 스타일링 팁을 소개합니다...',
          imageUrl: 'assets/images/wedding_post1.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 1)),
          likes: 342,
          comments: 58,
        ),
        SelfBrandPost(
          id: '2',
          title: '웨딩 예산 관리',
          content: '효율적인 웨딩 예산 설계와 관리 방법을 알려드립니다...',
          imageUrl: 'assets/images/wedding_post2.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 3)),
          likes: 287,
          comments: 45,
        ),
        SelfBrandPost(
          id: '3',
          title: '웨딩 촬영 준비',
          content: '완벽한 웨딩 촬영을 위한 준비사항과 팁을 공유합니다...',
          imageUrl: 'assets/images/wedding_post3.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 5)),
          likes: 265,
          comments: 39,
        ),
        SelfBrandPost(
          id: '4',
          title: '웨딩 음악 선곡',
          content: '결혼식의 순간을 더욱 특별하게 만들 음악 선곡 가이드...',
          imageUrl: 'assets/images/wedding_post4.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 7)),
          likes: 234,
          comments: 42,
        ),
        SelfBrandPost(
          id: '5',
          title: '하객 명단 관리',
          content: '효율적인 하객 명단 관리와 좌석 배치 방법을 설명합니다...',
          imageUrl: 'assets/images/wedding_post5.jpg',
          createdAt: DateTime.now().subtract(const Duration(days: 9)),
          likes: 198,
          comments: 31,
        ),
      ],
    ),
  };

  static List<SelfBrandProfile> getAllProfiles() {
    // 기존 프로필 리스트를 2번 반복
    final List<SelfBrandProfile> repeatedProfiles = [];
    final originalProfiles = _profiles.values.toList();

    // 첫 번째 세트
    // repeatedProfiles.addAll(originalProfiles);

    // 두 번째 세트 (ID와 phoneNumber를 수정하여 추가)
    for (var profile in originalProfiles) {
      repeatedProfiles.add(
        SelfBrandProfile(
          id: profile.id,
          moveNumber: profile.moveNumber,
          phoneNumber: profile.phoneNumber,
          title: profile.title,
          backgroundImage: profile.backgroundImage,
          description: profile.description,
          telegramUrl: profile.telegramUrl,
          xUrl: profile.xUrl,
          youtubeUrl: profile.youtubeUrl,
          homepageUrl: profile.homepageUrl,
          posts: profile.posts,
        ),
      );
    }

    return repeatedProfiles;
  }

  static SelfBrandProfile? getProfile(String phoneNumber) {
    return _profiles[phoneNumber];
  }
}
